### ISSUE TITLE
createConnection is not a function

### ISSUE THREAD

**Issue by softwaretech** [veeraRaghavSanthosh/sharepointConnector#10]
Greetings,

I am trying to log in, however, in all fairness, I'm not 100% sure I should be using NTLM however, I get a response that simply states this.createConnection is not a function.

TypeError: this.createConnection is not a function
at Object.createSocket (_http_agent.js:227:26)
at Object.addRequest (_http_agent.js:185:10)
at new ClientRequest (_http_client.js:249:16)
at Object.request (https.js:289:10)
at Request.start (C:\xampp\htdocs\api\node_modules\request\request.js:751:32)
at Request.end (C:\xampp\htdocs\api\node_modules\request\request.js:1511:10)
at end (C:\xampp\htdocs\api\node_modules\request\request.js:564:14)
at Immediate._onImmediate (C:\xampp\htdocs\api\node_modules\request\request.js:578:7) at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)

Any guidance?

Thanks!!

**Comment by nickperkinslondon** [comment]
I also get this result.  Time to move on to one of the many other Sharepoint libraries, I guess.  In general I am becoming very frustrated trying to find an easy NodeJS/Sharepoint library!
